R-Giacomin/menu-ms

Gemfile, Gemfile.lock, db/migrate/20200930145210_add_collumns_to_users.rb, db/schema.rb
Acrescentei as colunas cpf e manager (com valor default false) no model User.
Também acrescentei uma gem para criar cpf faker para usar depois no seed
=> model user change and gem cpf faker

app/models/base.rb, app/models/item.rb, app/models/order.rb, app/models/user.rb, app/models/variable.rb, db/migrate/20200929201555_create_bases.rb, db/migrate/20200929203131_create_orders.rb, db/migrate/20200929203452_create_variables.rb, db/migrate/20200929204022_create_items.rb, db/schema.rb, test/models/base_test.rb, test/models/item_test.rb, test/models/order_test.rb, test/models/variable_test.rb
Criados os modelos.  Falta adicionar todas as validações.
=> Adicionados modelos Base Variable Order e Items

app/controllers/bases_controller.rb, config/routes.rb, test/controllers/bases_controller_test.rb
Eu e Fabi fizemos router de base e BasesController.
=> BasesController e Router

app/controllers/bases_controller.rb, app/models/base.rb, app/views/bases/index.html.erb, db/schema.rb
=> correção da validação do modelo de base

app/views/bases/show.html.erb, db/schema.rb
Show inicial de bases a ser aprimorado.
=> add inicial show view Bases

db/seeds.rb
Inseri mais 3 bases no seed e excluí uma que era de dados agregados.
=> seed with 4 bases

app/views/bases/index.html.erb
=> link para show de variáveis

app/controllers/items_controller.rb, app/views/bases/show.html.erb, config/routes.rb, test/controllers/items_controller_test.rb
Tentativa de criação de items, ainda não funcionando.
=> criate items not working

app/controllers/items_controller.rb, app/controllers/orders_controller.rb, app/views/bases/show.html.erb, app/views/orders/index.html.erb, config/routes.rb
Consertado o funcionamento do botão "Pedir esta base" da view bases. Ajustes  dos controllers Items e Orders.
=> items controller método destroy. Orders controller ajustado

app/views/orders/index.html.erb, db/seeds.rb
Fiz algumas alterações de css na order para ficar mais no padrão.
Comentei a criação de orders e items no seed.
Notei um problema no schema, que estava incompatível, para mim pelo menos, em relação aos arquivos migrate. Corrigiu fazendo o drop na base e depois create e migrate.
=> some css in orders

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/views/bases/index.html.erb, app/views/bases/show.html.erb, app/views/shared/_navbar.html.erb
=> estilos bases-index

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/application_controller.rb, app/views/bases/show.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/pages/home.html.erb
Fiz mais algumas mudanças de css
=> More features

app/assets/stylesheets/components/_cards.scss, app/views/orders/index.html.erb, app/views/orders/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> Ajustes finais

Gemfile.lock, app/controllers/bases_controller.rb, app/models/base.rb, app/views/bases/new.html.erb
Fizemos o formulário para cadastro de uma nova base. 
Não conseguimos avançar porque está dando problema no elastic search. Faltou a configuração.
Falta código para que após gravar o arquivo csv, esse arquivo alimente a variables.
Gabi
=> formulário de cadastro de nova base

Gemfile, app/controllers/bases_controller.rb, app/models/base.rb, app/models/user.rb, app/views/pages/home.html.erb, config/routes.rb
Implementado autocomplete no elasticsearch.   Falta ajustar o css para aparecerem as letras.
=> Elastic search

app/controllers/bases_controller.rb, db/schema.rb
Add create action in base Controller
=> Add create action in base Controller

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/shared/_navbar.html.erb
Tradução das views de usuário e possibilidade de adicionar e editar foto de perfil.
=> interfaces do usuário e avatar

app/assets/stylesheets/components/_table.scss, app/controllers/bases_controller.rb, app/controllers/orders_controller.rb, app/models/base.rb, app/views/bases/_cindex.html.erb, app/views/bases/show.html.erb, app/views/orders/edit.html.erb, app/views/orders/index.html.erb, config/routes.rb, db/migrate/20201006175837_add_periodicity_to_bases.rb, db/migrate/20201006203455_add_period_to_orders.rb, db/schema.rb, db/seeds.rb
Inclusão de periodicidade em bases e período em orders.
Criação de formulário de pedido, ainda não funcionando direito.
=> Periodicity

app/assets/stylesheets/pages/_about_us.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/about_us.html.erb, config/routes.rb
=> adicionada a página about us

app/views/pages/about_us.html.erb
alterado o style da página about us
=> alterado o style da página about us

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_order.scss, app/controllers/bases_controller.rb, app/controllers/orders_controller.rb, app/models/order.rb, app/views/bases/_form.html.erb, app/views/bases/show.html.erb, app/views/orders/edit.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, db/migrate/20201007132921_change_justify_to_be_text_in_orders.rb, db/schema.rb
Algumas melhorias na jornada do usuário até o formulário e views do pedido.
=> Formulario

app/controllers/pages_controller.rb
Corrigido fechamento do bloco @bases.each do |base|.  Estava faltando um end.
=> Acerta pages controller

app/assets/stylesheets/components/_footer.scss, app/controllers/pages_controller.rb, app/views/orders/edit.html.erb, app/views/orders/index.html.erb, app/views/shared/_footer.html.erb
Algumas alterações na view do formulário e footer
=> link about_us end formulario

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/views/pages/about_us.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
Ajustes do footer, banner, navbar, criação do navbar-faker.
=> ajustes footer,colors,navbar, navbar-faker

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb, app/views/pages/manager.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Fiz uns ajustes de css na página inicial e criei página para o gestor quando não logado, com link na página inicial.
=> Home manager

app/views/bases/_form.html.erb, db/seeds.rb, lib/seeds/DENGUE_1.csv, lib/seeds/SIM_1.csv, lib/seeds/SINAN_TB_1.csv, lib/seeds/SINASC_1.csv
Quatro novas bases inseridas no seed: SIM, SINASC, SINAN Tuberculose, SINAN Dengue
=> mais 4 bases novas no seed

lib/seeds/SIM_1.csv
Dados cadastrais na base do SIM
=> seed do sim alterado

app/assets/stylesheets/components/_footer.scss, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
alterado css do footer e texto dos cards
=> alterado css do footer e texto dos cards

app/assets/stylesheets/components/_footer.scss, app/views/orders/edit.html.erb, app/views/orders/terms.html.erb, app/views/pages/home.html.erb, db/seeds.rb
cards home ok e todos botões roxos
=> cards home ok e todos botões roxos

app/assets/stylesheets/components/_footer.scss, app/views/layouts/application.html.erb
=> Footer stick to botton

app/views/pages/about_us.html.erb
Refatorei o código e ajustei os cartões para o mesmo tamanho.
=> Same cards size
